# Generated by Django 5.0.4 on 2024-04-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_course_id_course_course_oasis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rubric',
        ),
        migrations.AlterField(
            model_name='uploadedmaterial',
            name='file',
            field=models.FileField(upload_to='templates/courses/materials/'),
        ),
    ]
