# Generated by Django 5.0.4 on 2024-05-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_student_assignment_student_quiz_delete_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmaterial',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student_assignment',
            name='grade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_quiz',
            name='grade',
            field=models.TextField(),
        ),
    ]
